
services:
  daveedg-portfolio:
    build:
      context: ..
      args:
          - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
          - AUTH_PASSWORD=${AUTH_PASSWORD}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    restart: unless-stopped