name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}        # e.g., 153.92.223.133
          username: ${{ secrets.VPS_USER }}      # e.g., "David" or your deployment user
          key: ${{ secrets.VPS_SSH_KEY }}        # your private SSH key (with proper line breaks)
          script: |
            cd /srv/daveedg.com
            sudo chown -R ${USER}:${USER} /srv/daveedg.com/
            git config --global --add safe.directory /srv/daveedg.com
            [ -d public/Projects ] && mv public/Projects public/projects
            git fetch origin
            git reset --hard origin/main
            cd infra
            export AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}
            export NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
            export CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            export CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            docker compose down
            docker system prune -f --volumes
            docker compose build --no-cache
            docker compose up -d